# Unified Application Configuration
application:
  name: DevOpsSimulator
  version: 3.0.0-experimental
  environment: production
  experimental_mode: false
  
server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true
  # Experimental multi-port support
  multi_port: [9000, 9001, 9002]
  
logging:
  level: INFO
  format: json
  # Optional experimental structured logging
  experimental_logging:
    level: TRACE
    format: structured
    output: /var/log/experimental.log
    ai_analysis: disabled

database:
  host: prod-db.example.com
  port: 5432
  name: devops_prod
  # Optional experimental distributed DB
  distributed: false

features:
  auto_scaling: true
  load_balancer: enabled
  backup_enabled: true
  # Optional experimental features
  chaos_engineering: false

development:
  enabled: false
  port: 3000
  hot_reload: false
  debug_mode: false
  mock_apis: false

ai_features:
  predictive_scaling: false
  anomaly_detection: false
  auto_optimization: false
  model_version: "v2.1.0"

cloud_providers:
  - aws
  - azure
  - gcp

security:
  zero_trust: enabled
  encryption: AES-256
  audit_logging: comprehensive
